name: Compile mtftar

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up build environment
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Compile mtftar
      run: make

    - name: Upload mtftar artifact
      uses: actions/upload-artifact@v2
      with:
        name: mtftar
        path: ./mtftar
