name: Compile mtftar

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up build environment
      run: sudo apt-get update && sudo apt-get install -y build-essential autoconf

    - name: Generate configure script
      run: autoreconf -i

    - name: Configure the build
      run: ./configure

    - name: Compile mtftar
      run: make
